### ISSUE TITLE
HDMI port enabling

### ISSUE THREAD

**Issue by ravnized** [nekiro/Xiaomi-Notebook-Pro-15-6-Enhanced-Hackintosh#1]
I suggest to change the smbios to `macbookpro 15,2`
and add into deviceProperties
`<dict>
<key>AAPL,ig-platform-id</key>
<data>AACbPg==</data>
<key>model</key>
<string>Intel UHD 620</string>
<key>device-id</key>
<data>mz4AAA==</data>
<key>disable-external-gpu</key>
<data>AQAAAA==</data>
<key>enable-hdmi20</key>
<data>AQAAAA==</data>
<key>framebuffer-con1-busid</key>
<data>AQAAAA==</data>
<key>framebuffer-con1-enable</key>
<data>AQAAAA==</data>
<key>framebuffer-con1-type</key>
<data>AAgAAA==</data>
<key>framebuffer-fbmem</key>
<data>AACQAA==</data>
<key>framebuffer-patch-enable</key>
<data>AQAAAA==</data>
<key>framebuffer-stolenmem</key>
<data>AAAwAQ==</data>
<key>hda-gfx</key>
<string>onboard-1</string>
</dict>`
And if the hdmi still doens't work i suggest to use the bootflag `-wegnoegpu`

**Comment by nekiro** [comment]
I used these settings and HDMI still does not work. DGPU is disabled via acpi patch not boot arg.

**Comment by ravnized** [comment]
using it now and its working

**Comment by nekiro** [comment]
Alright. I will try it. Thanks
